<a href="https://colab.research.google.com/github/Muneebaslam470/Calculator/blob/main/DemocodeNN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
      super().__init__()
      self.linear = nn.Linear(num_features, 1)
      self.sigmoid = nn.Sigmoid()

  def forward(self, features):

      out = self.linear(features)
      out = self.sigmoid(out)

      return out

In [25]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)


tensor([[0.5684],
        [0.5949],
        [0.5222],
        [0.6497],
        [0.5484],
        [0.5793],
        [0.6060],
        [0.5731],
        [0.6154],
        [0.5434]], grad_fn=<SigmoidBackward0>)

In [26]:
model.linear.weight

Parameter containing:
tensor([[-0.2245,  0.1159, -0.0743,  0.3843, -0.1561]], requires_grad=True)

In [27]:
model.linear.bias

Parameter containing:
tensor([0.3491], requires_grad=True)

In [28]:
!pip install torchinfo

In [30]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00